# 相对固定的配置
project:
  # 项目描述
  description: Summer权限管理系统
  # 项目LICENSE
  license: MulanPSL2
  # 项目版本
  version: "@project.version@"

application:
  cache:
    # 缓存类型，值：REDIS/HEAP
    # 使用HEAP（堆内缓存）的注意事项：
    #    1.在应用集群部署时数据无法共享！
    #    2.在应用关闭或重启时数据会丢失！
    #    3.当且仅当“应用单机部署且不想依赖Redis”或“集群部署作为Redis的次级缓存”时推荐使用！
    type: REDIS
  oss:
    # 对象存储类型，值：LOCAL/MIN_IO/QI_NIU
    type: LOCAL

server:
  # Tomcat
  tomcat:
    threads:
      # 最大工作线程（并发）
      max: 1000
      # 最小工作线程
      min-spare: 30
  # 最大请求头大小
  max-http-header-size: 10KB
  # Servlet
  servlet:
    context-path: /summer
    session:
      cookie:
        http-only: true

spring:
  # Jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    # 文件上传
    multipart:
      # 单个文件最大限制
      max-file-size: 30MB
      # 请求最大限制
      max-request-size: 100MB
  # 消息国际化
  messages:
    encoding: UTF-8
    basename: i18n/messages,i18n/validation
  main:
    # 不允许同名Bean覆盖
    allow-bean-definition-overriding: false
  autoconfigure:
    # 排除自动装配
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  datasource:
    # 多数据源
    dynamic:
      # 必须严格匹配所有数据源
      strict: true
      # 连接池配置
      hikari:
        # 配置项说明参考 com.zaxxer.hikari.HikariConfigMXBean
        connection-timeout: 10000
        validation-timeout: 3000
        idle-timeout: 60000
        max-lifetime: 180000
        max-pool-size: 10
        min-idle: 5
  # Redis，只有application.cache.type: REDIS 时会生效
  redis:
    timeout: 6000
    lettuce:
      # 连接池配置
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 1000
        max-wait: -1

# MybatisPlus
mybatis-plus:
  # Entity扫描，多个package用“,”或者“;”分隔
  typeAliasesPackage: me.xiajhuan.summer.**.entity
  # Mapper.xml文件位置，多个location用“,”分隔
  mapperlocations: classpath*:/mapper/*/*.xml
  global-config:
    # 数据库相关配置
    db-config:
      # 全局主键ID类型
      id-type: ASSIGN_ID
    # 关闭LOGO
    banner: false
  # Mybatis原生配置
  configuration:
    # 驼峰转下划线
    map-underscore-to-camel-case: true
    # 全局缓存
    cache-enabled: false
    # 指定当结果集中值为 null 的时候是否调用映射对象的 setter（map 对象时为 put）方法
    call-setters-on-nulls: true
    # 当没有为参数指定特定的 JDBC 类型时，空值的默认 JDBC 类型
    jdbc-type-for-null: NULL

batch:
  # 批量操作限制
  limit:
    # 每次批量插入数（JDBC批量提交）
    real-save-num-every-time: 100
    # Excel最大导出数
    excel-max-export: 40000

fail:
  # 失败重试数
  retry-times:
    # 乐观锁
    optimistic-lock: 20
    # 调用外部Api
    call-outside-api: 5

mica:
  # XSS过滤
  xss:
    # 拦截的路由
    path-patterns: /**
    # 放行的路由
    path-exclude-patterns: /api/test/**

logging:
  # 日志级别
  level:
    org:
      springframework:
        context:
          # 屏蔽“is not eligible”日志
          support: warn

# 应用监控
management:
  endpoints:
    # 以web（Http接口）方式暴露所有端点
    web:
      exposure:
        include: '*'
      # 自定义前缀（安全性考虑）
      base-path: /appMonitor
  endpoint:
    # CacheManagers
    caches:
      enabled: false
    # Beans
    beans:
      enabled: true
    # 健康状况
    health:
      enabled: true
      show-details: ALWAYS
    # 应用信息
    info:
      enabled: true
    # Conditions
    conditions:
      enabled: true
    # 远程关闭应用（慎用）
    # curl -X POST http://localhost:6666/summer/appMonitor/shutdown
    shutdown:
      enabled: false
    # 应用配置
    configprops:
      enabled: true
    # 应用环境
    env:
      enabled: true
    # 应用日志
    loggers:
      enabled: true
    # 堆转储
    heapdump:
      enabled: false
    # 线程转储
    threaddump:
      enabled: false
    # 应用指标
    metrics:
      enabled: true
    # 定时任务（Quartz）
    quartz:
      enabled: true
    # 定时任务（Spring）
    scheduledtasks:
      enabled: false
    # 请求映射
    mappings:
      enabled: true