# 开发环境
spring:
  datasource:
    # 多数据源
    dynamic:
      # Sql打印
      p6spy: true
      # 默认数据源
      primary: business
      datasource:
        # business模块数据源
        business:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://origin-1:3306/summer-business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: asda1992
        # system模块数据源
        system:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://origin-1:3306/summer-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: asda1992

# Redis，只有application.cache.type: REDIS时会生效
redis:
  password: asda1992
  # 模式，值：STANDALONE/CLUSTER
  mode: STANDALONE
  # 单机模式，只有redis.mode: STANDALONE时会生效
  standalone:
    host: origin-1
    port: 6379
    database: 0
  # 集群模式，只有redis.mode: CLUSTER时会生效
  cluster:
    node-set: docker-1:6381,docker-1:6382,docker-1:6383,docker-1:6384,docker-1:6385,docker-1:6386

# 定时任务启动
quartz-startup:
  auto: false
  delay: 20

logging:
  # 日志级别
  level:
    me:
      xiajhuan:
        summer:
          # core模块
          core:
            # Excel
            excel: debug
            # 限流
            ratelimiter: debug
            # 工具
            utils: info
          # system模块
          system:
            # handler
            handler:
              # 异常处理
              exception: info
          # admin模块
          admin:
            # api
            api: info
            # business
            business: info
            # task
            task: info