# 相对固定的配置
project:
  # 项目描述
  description: Summer权限管理系统
  # 项目LICENSE
  license: MulanPSL2
  # 项目版本
  version: "@project.version@"

server:
  # 最大请求头大小
  max-http-header-size: 10KB
  # Servlet
  servlet:
    context-path: /summer
    session:
      cookie:
        http-only: true

spring:
  # Jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # 文件上传
  servlet:
    multipart:
      # 单个文件最大限制
      max-file-size: 30MB
      # 请求最大限制
      max-request-size: 100MB
  # 消息国际化
  messages:
    encoding: UTF-8
    basename: i18n/messages,i18n/validation
  # 不允许同名Bean覆盖
  main:
    allow-bean-definition-overriding: false
  # 排除自动装配
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# MybatisPlus
mybatis-plus:
  # Entity扫描，多个package用“,”或者“;”分隔
  typeAliasesPackage: me.xiajhuan.summer.**.entity
  # Mapper.xml文件位置，多个location用“,”分隔
  mapperlocations: classpath*:/mapper/**/*.xml
  global-config:
    # 数据库相关配置
    db-config:
      # 全局主键ID类型
      id-type: ASSIGN_ID
    # 关闭LOGO
    banner: false
  # Mybatis原生配置
  configuration:
    # 驼峰转下划线
    map-underscore-to-camel-case: true
    # 全局缓存
    cache-enabled: false
    # 指定当结果集中值为 null 的时候是否调用映射对象的 setter（map 对象时为 put）方法
    call-setters-on-nulls: true
    # 当没有为参数指定特定的 JDBC 类型时，空值的默认 JDBC 类型
    jdbc-type-for-null: NULL

# XSS过滤
mica:
  xss:
    # 拦截的路由
    path-patterns: /**
    # 放行的路由
    path-exclude-patterns: /api/test/**