spring:
  datasource:
    # 多数据源
    dynamic:
      p6spy: true
      # 连接池配置
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
      # 默认数据源
      primary: business
      datasource:
        # business模块数据源
        business:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.142:3306/summer-business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: jack%2021#2@6XJH
        # common模块数据源
        common:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.142:3306/summer-common?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: jack%2021#2@6XJH

  # Redis配置，只有缓存类型为 REDIS 时才会生效
  redis:
    host: 192.168.0.7
    port: 6379
    password: jack_2021
    database: 2
    timeout: 5000
    lettuce:
      # 连接池配置
      pool:
        min-idle: 8
        max-idle: 20
        max-active: 1000
        max-wait: 5000

server:
  # Tomcat
  tomcat:
    threads:
      # 最大工作线程（并发）
      max: 1000
      # 最小工作线程
      min-spare: 30
  # 缓存类型，值：REDIS/HEAP
  cache:
    type: REDIS

# 日志级别
logging:
  level:
    me:
      xiajhuan:
        summer:
          # summer-core日志
          core:
            # 限流日志
            ratelimiter: debug
          # summer-admin日志
          admin:
            # business模块日志
            business: info
            # common模块日志
            common: info
            # open模块日志
            open: info



