# 生产环境
spring:
  datasource:
    # 多数据源
    dynamic:
      # Sql打印
      p6spy: false
      # 默认数据源
      primary: business
      datasource:
        # business模块数据源
        business:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://origin-1:3306/summer-business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: asda1992
        # system模块数据源
        system:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://origin-1:3306/summer-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: asda1992
  # Redis，只有application.cache.type: REDIS时会生效
  redis:
    host: origin-1
    port: 6379
    password: asda1992
    database: 0

quartz:
  # 定时任务启动
  startup:
    auto: true
    delay: 20

logging:
  # 日志级别
  level:
    me:
      xiajhuan:
        summer:
          # core模块
          core:
            # Excel
            excel: info
            # 限流
            ratelimiter: info
            # 工具
            utils: info
          # system模块
          system:
            # handler
            handler:
              # 异常处理
              exception: info
          # admin模块
          admin:
            # api
            api: info
            # business
            business: info
            # task
            task: info