# 预发布环境
spring:
  datasource:
    # 多数据源
    dynamic:
      # Sql打印
      p6spy: false
      # 默认数据源
      primary: business
      datasource:
        # business模块数据源
        business:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.142:3306/summer-business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: jack%2021#2@6XJH
        # system模块数据源
        system:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.142:3306/summer-system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: jack%2021#2@6XJH
  # Redis，只有server.cache.type: REDIS 时会生效
  redis:
    host: 192.168.0.7
    port: 6379
    password: jack_2021
    database: 2

quartz:
  # 定时任务启动
  startup:
    auto: true
    delay: 20

logging:
  # 日志级别
  level:
    me:
      xiajhuan:
        summer:
          # core模块
          core:
            # Excel
            excel: info
            # 限流
            ratelimiter: info
          # system模块
          system:
            # common
            common:
              # 异常处理
              handler: info
          # admin模块
          admin:
            # api
            api: info
            # business
            business: info
            # task
            task: info