server:
  port: 6666

spring:
  application:
    name: summer-admin
  profiles:
    # 包含 application-core.yml
    include: core
    # 环境 dev/test/prod
    active: dev

# 指标监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
