server:
  # 服务端口
  port: 6666

spring:
  application:
    name: Summer
  profiles:
    # 包含其他配置，多个用“,”分隔
    include: fixed,custom
    # 环境 dev/test/pre/prod
    active: dev

# 指标监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
